<a href="https://colab.research.google.com/github/SambhavSharma1/data-visualization/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from pandas import Series

In [ ]:
# first question
sales = Series([120,150,180,210])
sales

0    120
1    150
2    180
3    210
dtype: int64

In [ ]:
# second question
marks  = Series([72,81,60,90])
marks.values

array([72, 81, 60, 90])

In [ ]:
# third question
marks.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
#fourth question
temp =Series([28,31,30,20],index =['mon','tue','wed','thu'])
temp

In [ ]:
#fifth question
population = Series([35, 42, 31], index=['Delhi','Mumbai','Jaipur'])
population['jaipur']

In [ ]:
#6th question
score = Series([35,68,44,79,52])
score[score>50]

In [ ]:
#7th question
subjects =  Series([76,83,91],index=['physics','chemistry','maths'])
print('chemistry'in subjects)

True

In [ ]:
#8th question
Series.to_dict(subjects)

{'physics': 76, 'chemistry': 83, 'maths': 91}

In [ ]:
# 9th question
prices  = {'pen':10,'notebook':55,'bag':700}
p_series = Series(prices)
prices
p_series

pen          10
notebook     55
bag         700
dtype: int64

In [ ]:
#11th question
data  = {'A':10,'B':20,'c':30}
s = Series(data,index = ['A','B','C','D'])
pd.isnull(data)

False

In [ ]:
#14th question
sales = Series([88,21,2,1,2,233,3])
sales.name = 'monthly sales'
sales

0     88
1     21
2      2
3      1
4      2
5    233
6      3
Name: monthly sales, dtype: int64

In [ ]:
#question 15
sales.index.name = 'month'
sales

month
0     88
1     21
2      2
3      1
4      2
5    233
6      3
Name: monthly sales, dtype: int64

In [ ]:
#question 16
s = Series([18,45,27,61],index = ['P','Q','R','S'])
s[s>30]

Q    45
S    61
dtype: int64

In [ ]:
# question 17
s = Series([500,600,700],index = ['EAST','WEST','NORTH'])
print('WEST'in s)
print(500 in s)

True
False

In [ ]:
#question 18
city_data = {'delhi':80,'pune':65,'kochi':70}
city_s = Series([80,65,70],index = ['delhi','pune','kochi'])
print(city_data)
print(city_s)

{'delhi': 80, 'pune': 65, 'kochi': 70}
delhi    80
pune     65
kochi    70
dtype: int64

In [ ]:
#question 19
s = Series({'w':5,'x':10,'y':15},  index = ['w','x','y','z'])
print(s)
print(pd.isnull(s))

w     5.0
x    10.0
y    15.0
z     NaN
dtype: float64
w    False
x    False
y    False
z     True
dtype: bool

In [ ]:
#question 21
s1 = Series([10,20,30],index = ['A','B','C'])
s2 = Series([1,2,3],index = ['C','A','B'])
print(s1+s2)

A    12
B    23
C    31
dtype: int64

In [ ]:
#question 22
s1 = Series({'a':12,'b':18})
s2 = Series({'b':5,'c':9})
print(s1+s2)

a     NaN
b    23.0
c     NaN
dtype: float64

In [ ]:
# question 23
stock = Series([25,40,18] ,index = ['item1','item2','item3'])
stock_dict = Series.to_dict(stock)
print(stock_dict)
stock2 = Series(stock_dict)
print(stock2)

{'item1': 25, 'item2': 40, 'item3': 18}
item1    25
item2    40
item3    18
dtype: int64

In [ ]:
#question 24
marks = {'maths':88,'science':74,'english':69,'history':81}
marks_series = Series([88,74,69,81],index = ['history','english','science','maths'])
print(marks_series)
print(marks_series[marks_series>70])

history    88
english    74
science    69
maths      81
dtype: int64
history    88
english    74
maths      81
dtype: int64

In [ ]:
#question 25
rev = pd.Series([50000, 75000, 60000],
                index=["Delhi", "Mumbai", "Jaipur"])
rev.name = "Revenue"
rev.index.name = "Branch"
print(rev)

Branch
Delhi     50000
Mumbai    75000
Jaipur    60000
Name: Revenue, dtype: int64

In [ ]:
#question 26
north  = Series({'jan':40,'feb':55,'mar':60})
south  = Series({'feb':20,'mar':25,'apr':60})
total= north+south
print(total)

apr     NaN
feb    75.0
jan     NaN
mar    85.0
dtype: float64

In [ ]:
#question 27
d = {'red':12,'blue':18,'green':24}
labels = ['green','red','yellow','blue']
result = Series(d,index = labels)
print(result)

green     24.0
red       12.0
yellow     NaN
blue      18.0
dtype: float64

In [ ]:
#question 29
import pandas as pd

# Create a labelled Series
sales = pd.Series([450, 700, 550, 300],index=["Laptop", "Mobile", "Tablet", "Keyboard"])



print(sales.values)
print(sales.index)
print(sales["Mobile"])
print(sales[sales > 500])
print("Laptop" in sales.index)
print(sales.to_dict())

[450 700 550 300]
Index(['Laptop', 'Mobile', 'Tablet', 'Keyboard'], dtype='object')
700
Mobile    700
Tablet    550
dtype: int64
True
{'Laptop': 450, 'Mobile': 700, 'Tablet': 550, 'Keyboard': 300}

In [ ]:
#question 30
data  = {'a':15,'b':35,'c':25}
s = Series(data ,index = ['c','a','d','b'])
s.name  = 'obserivations'
s.index.name = 'category'
print(s)

category
c    25.0
a    15.0
d     NaN
b    35.0
Name: obserivations, dtype: float64